version: "3.9"
services:
  proxy:
    image: traefik:latest
    command: --providers.file.filename=/etc/traefik/traefik-dadlex.yml #--api.dashboard=true --api.insecure=true
    ports:
      - ${DADLEX_PORT:-3000}:80
    volumes:
      - ./docker/traefik-proxy.yml:/etc/traefik/traefik-dadlex.yml
    networks:
      - public
      - internal
    depends_on:
      - frontend
      - backend
  frontend:
    image: "ghcr.io/exanion/dadlex-frontend:${PACKAGE_VERSION:-latest}"
    networks:
      - internal
  backend:
    image: "ghcr.io/exanion/dadlex-backend:${PACKAGE_VERSION:-latest}"
    networks:
      - internal
    environment:
      - MONGODB_CONNECTION=mongodb://database/dadlex
      - LOG_LEVEL=${BACKEND_LOG_LEVEL:-info}
      - BACKEND_PUBLIC_URL
      - FRONTEND_PUBLIC_URL
      - AUTH_ISSUER_BASEURL
      - AUTH_CLIENT_ID
      - AUTH_CLIENT_SECRET
      - CAL_MS_TENANT_ID
      - CAL_MS_CLIENT_ID
      - CAL_MS_CLIENT_SECRET
      - CAL_GOOGLE_CLIENT_ID
      - CAL_GOOGLE_CLIENT_SECRET
    volumes:
      - ./data/backend-secrets:/app/secrets
    depends_on:
      - database
  database:
    image: "mongo"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - internal
networks:
  internal: null
  public: null