version: "3.9"
services:
  frontend:
    image: "dadlex-frontend"
    ports:
      - "${DADLEX_FRONTEND_PORT}:3000"
    networks:
      - frontend
  backend:
    image: "dadlex-backend"
    ports:
      - "${DADLEX_BACKEND_PORT}:3000"
    networks:
      - backend
    environment:
      - MONGODB_CONNECTION=mongodb://database/dadlex
    depends_on:
      - database
  database:
    image: "mongo"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - backend
networks:
  frontend: null
  backend: null
