name: lint-commits
on:
  push:
    branches-ignore:
      - "release-*.*.*"
      - "main"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Yarn Install
        run: |
          yarn install
      - name: Lint
        run: |
          yarn lint
