name: 'Storybook Chromatic Publish'
on:
  push:
    paths:
      - "frontend/**"
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        working-directory: ./frontend
      - uses: chromaui/action@v1
        with:
          workingDir: ./frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}