name: Test docs deployment

on:
  pull_request:
    branches:
      - dev
jobs:
  test-docs:
    name: Test docs deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        working-directory: ./docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: ./docs
        run: yarn build
